name: Deploy Azure Resources

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: 'Deploy Azure resources'
        required: true
        default: 'false'


permissions:
  id-token: write
  contents: read
  checks: write
  issues: read
  packages: read

jobs:
  detectenv:
    runs-on: ubuntu-latest